apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: luqwjbgqp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: luqwjbgqp-nodejs 
  name: luqwjbgqp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: luqwjbgqp-nodejs 
